apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flux
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-flux
  template:
    metadata:
      labels:
        app: demo-flux
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
