apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flux
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-flux
  template:
    metadata:
      labels:
        app: demo-flux
    spec:
      containers:
        - name: nginx
          image: nginx:1:28
          ports:
            - containerPort: 80
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-flux
                  key: SECRET
            - name: STAGE
              value: K8S
