apiVersion: v1
data:
    SECRET: ENC[AES256_GCM,data:JDdt1VPM380=,iv:HRcTcWvMlU5IL6NlJj7d0hmc5G70fNbUwOfvnSXk6RE=,tag:BkL98N/9EE4CsKpYEw121A==,type:str]
kind: Secret
metadata:
    name: demo-flux
sops:
    age:
        - recipient: age1z79gugmjumk65xnd9nlsd3uh8xkm4j5eu4gcv3888am66ywc3g4qll7pmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckM4UU9kOG10WlllN1Z2
            a056VWRxY3B5aS9ISDNqbEZvS2FtK0R1RGlBCk1qcWYxaFQxWHR4TXd5b2NIWTF3
            SW5reHpwQW1iNkFhdmlWRHV6elBFckkKLS0tIGhrNDA5dVNMVTVkTWp0M25iU293
            Q0Y3ZWhxR0FnaVlETDAwQTJUNUJ5bXcKB+WaE+qffmyIkC2gZgR0C4IHx2NSaaCV
            rrTjSmRKKwCyCHPMmo9iDBaK+Qj17mwQtxyiTk8fn1hEPit/krxA4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T15:33:13Z"
    mac: ENC[AES256_GCM,data:gMXCCROTReNm6toGIDfI2mTfI2EfQtOrHRaq3w5gCOeJaD/lRp67+65VNuCW+mPHd7Rb/sAO819Nr6bnmgJFSK74gpmQMWMuC2edcyL/43Ead5yHzLpwTTcSYmEhs97dM6DTnRI+ELhj5GOwWnELBr5rFODYk+LoMCqApVS/++I=,iv:k6LVfCQeDVeBf1arcWKZfwk3nVFuMv7WO2SIqd2IGwE=,tag:4DSBHbxgcS89H7DJ/fuMFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
